services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
